name: x86-64 Pull and Save Docker Image
on:
  workflow_dispatch:
    inputs:
      docker_images:
        description: '请填写docker镜像名称 多个用英文逗号分开'
        required: true
        default: 'alpine:latest'  # 设置默认的 Docker 镜像列表
      docker_name:
        description: '请填写docker.io用户名'
        required: true
        default: 'User_name'  # 设置默认的 Docker 镜像密码        
      docker_pwd:
        description: '请填写docker.io密码'
        required: true
        default: 'pwd-123456'  # 设置默认的 Docker 镜像密码
        

jobs:
  pull_and_package:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Docker Login
      # You may pin to the exact commit or the version.
      # uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
      uses: docker/login-action@v3.3.0
      with:
        registry: docker.io
        username: ${{ github.event.inputs.docker_name }}
        password: ${{ github.event.inputs.docker_pwd }}

          
    - name: Clean up Docker to free space
      run: |
          docker system prune -a -f
          docker volume prune -f

    - name: Pull Docker Images and Package
      run: |
        images="${{ github.event.inputs.docker_images }}"
        IFS=',' read -r -a image_array <<< "$images"
        for image in "${image_array[@]}"; do
          docker pull "${image}" --platform "linux/amd64"
          docker save "${image}" -o "${image//\//_}-amd64.tar"
        done

    - name: Compress the TAR files
      run: tar -czf x86-64-images.tar.gz *-amd64.tar

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: docker-images-tar
        path: x86-64-images.tar.gz
        retention-days: 1  # 将保留天数设置为 1 天 最多可设置90天

    - name: Docker LogOut
      # You may pin to the exact commit or the version.
      # uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
      uses: docker/login-action@v3.3.0
      with:
        registry: docker.io
        logout: true

    - name: Clean up intermediate files
      run: |
        rm *-amd64.tar
